// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-y6Jyb6Ut6jzxVYgNlsbvmCFVbNHTgzU',
    appId: '1:846619012509:web:85e2914b7516b9b28dd374',
    messagingSenderId: '846619012509',
    projectId: 'loginsignup-37be7',
    authDomain: 'loginsignup-37be7.firebaseapp.com',
    storageBucket: 'loginsignup-37be7.firebasestorage.app',
    measurementId: 'G-QL9CR789PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrov2PSW0y8tvKoZNWEZJYuNhoBlo3AQc',
    appId: '1:846619012509:android:5671e204481ebbac8dd374',
    messagingSenderId: '846619012509',
    projectId: 'loginsignup-37be7',
    storageBucket: 'loginsignup-37be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRGixc_pwnALDCbZ8B1q_D-LDqa1hZRQ',
    appId: '1:846619012509:ios:5cc6b41d96c8a4278dd374',
    messagingSenderId: '846619012509',
    projectId: 'loginsignup-37be7',
    storageBucket: 'loginsignup-37be7.firebasestorage.app',
    iosBundleId: 'com.example.internshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRGixc_pwnALDCbZ8B1q_D-LDqa1hZRQ',
    appId: '1:846619012509:ios:5cc6b41d96c8a4278dd374',
    messagingSenderId: '846619012509',
    projectId: 'loginsignup-37be7',
    storageBucket: 'loginsignup-37be7.firebasestorage.app',
    iosBundleId: 'com.example.internshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-y6Jyb6Ut6jzxVYgNlsbvmCFVbNHTgzU',
    appId: '1:846619012509:web:e0db3ba6bbbcc0d28dd374',
    messagingSenderId: '846619012509',
    projectId: 'loginsignup-37be7',
    authDomain: 'loginsignup-37be7.firebaseapp.com',
    storageBucket: 'loginsignup-37be7.firebasestorage.app',
    measurementId: 'G-TF6NQXC5J1',
  );
}
